# Generated by Django 6.0.1 on 2026-01-24 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='tags',
        ),
    ]
